### ISSUE TITLE
Problem print pdf invoice

### ISSUE THREAD

**Issue by lucav90** [magespecialist/m2-MSP_CashOnDelivery#10]
Hi,
i don't display the 'Cash on delivery' item (in the invoice totals block) on the invoice pdf print.
How can i solve?

**Comment by lucav90** [comment]
Hi,
some solution?

**Comment by phoenix128** [comment]
Hello @lucav90 ,
you are right, it seems we are missing totals in PDF.

We are working on it.

**Comment by pfandl** [comment]
i issued a pull request for the issue, if it doesn't go through here is how you can do it if you are in a hurry: http://webkul.com/blog/add-custom-fee-downloaded-pdf-order-magento2/
