### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by drgiorgini** [magespecialist/m2-MSP_CashOnDelivery#11]
installed on magento 2.1.1

It works fine but if I click on recent orders in customer account I get this error:
Fatal error: Class 'MSP\CashOnDelivery\Block\Sales\Order\Cashondelivery' not found in /home/magtest3/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93

**Comment by phoenix128** [comment]
Hello @drgiorgini,
please upgrade to last version, this bug has been solved in 1.0.3

**Comment by drgiorgini** [comment]
it works
thanks
