### ISSUE TITLE
Fatal Error - logged user - my orders

### ISSUE THREAD

**Issue by teyogofy** [magespecialist/m2-MSP_CashOnDelivery#12]
Hi,
if I access as a registered user on frontend and i go in dashboard - my orders and select show order from the list i get this error:

Fatal error: Class 'MSP\CashOnDelivery\Block\Sales\Order\Cashondelivery' not found in /public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 93

magento 2.1.2, php 5.6.27 (previously also on magento 2.1.0)

thanks for helping

**Comment by phoenix128** [comment]
@teyogofy , did you upgrade to the very last version of MSP_CashOnDelivery? This bug should have been already solved.

**Comment by teyogofy** [comment]
My bad,
it is ok with the latest version
Thank you
