### ISSUE TITLE
How to change Cash On Delivery to Cash Deposit in order summary?

### ISSUE THREAD

**Issue by vivek28111992** [magespecialist/m2-MSP_CashOnDelivery#14]
I want to change text of Cash On Delivery to Cash Deposit in order summary.How do I do that?

**Comment by phoenix128** [comment]
You can:

- Edit `MSP\CashOnDelivery\Model\Total\Quote\CashOnDelivery` (disencouraged way)
- Insert a translation in your theme (suggested way)

**Comment by vivek28111992** [comment]
What do you mean by translation in your theme? Can you explain in detail, sorry I'm new to magento?

**Comment by slackerzz** [comment]
hi @vivek28111992 take a look at
http://devdocs.magento.com/guides/v2.1/frontend-dev-guide/translations/translate_practice.html
