### ISSUE TITLE
CashOnDelivery amount is added to Lifetime Sales

### ISSUE THREAD

**Issue by galanis-a** [magespecialist/m2-MSP_CashOnDelivery#18]
I am using Magento 2.1.3 and when i submit the invoice the cash on delivery fee is added to the Lifetime Sales in the Dashboard.

Example:

The item price is $45. The shipping cost is $5 and the cash on delivery fee $3.
When the order is invoiced the amount that is added in the Lifetime Sales is $48.

I am trying to solve this with no luck so far. I would like to here your suggestions.
Thank you.

**Comment by phoenix128** [comment]
It is a Magento 2 problem using `grand_total` - `shipping_cost`.

Look here: `Magento\Reports\Model\ResourceModel\Order\Collection::_calculateTotalsLive` and `Magento\Reports\Model\ResourceModel\Order\Collection::_calculateTotalsAggregated`.

You should rewrite with it a preference.

**Comment by galanis-a** [comment]
Thank you very much for @phoenix128!!! I was going crazy over this, i will try it.

**Comment by phoenix128** [comment]
If it fixes your problem please share it.

**Comment by galanis-a** [comment]
I am working currently on solving this but i can't figure it out.
I can't override the functions, _calculateTotalsLive and _calculateTotalsAggregated, with a plugin because they are protected. Also i can't override the class because it's a Collection.
I am stuck...
Any thoughts or suggestions will be appreciated.

**Comment by phoenix128** [comment]
Can't you create a preference on it?

**Comment by galanis-a** [comment]
When i try to override the Magento\Reports\Model\ResourceModel\Order\Collection class with a preference it gives me an error.

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Magento\\Backend\\Helper\\Dashboard\\Order::__construct() must be an instance of Magento\\Reports\\Model\\ResourceModel\\Order\\Collection

**Comment by phoenix128** [comment]
It is becasuse your new preferenced class should extend `Magento\Reports\Model\ResourceModel\Order\Collection`

Or you did not:

- Flushed cache
- Cleared var/generation

**Comment by galanis-a** [comment]
Yes i just figured that out thank you!

**Comment by galanis-a** [comment]
I did it!! I will test it further and i will create a pull request when it is ready to check it out.

**Comment by phoenix128** [comment]
Good job... waiting for the pull request!

**Comment by galanis-a** [comment]
The pull request #19 is the on with my solution with this problem

**Comment by phoenix128** [comment]
Your merge has been accepted.
Thank you for your contribution.
