### ISSUE TITLE
"Cash on delivery" always added on "order Summary"

### ISSUE THREAD

**Issue by rumbdev** [magespecialist/m2-MSP_CashOnDelivery#21]
hi there!
using Magento 2.1.4 we noticed that "Cash on delivery" is added to "Order Summary" before selecting the "Payment method".
It gets removed when selecting a different method, though it shouldn't be added automatically (to the "Order Summary") but only after choosing the "Cash on delivery" payment method.
I reckon it can be considered a bug. I tried to fix it with no avail.
cheers!

**Comment by matin73** [comment]
this bug is also on magento 2.1.5. any solution yet?

**Comment by phoenix128** [comment]
We tried to reproduce this bug with a 2.1.5 with no success.
Can you please give us an extact procedure to reproduce it?
Thanks.

**Comment by geo110** [comment]
This bug is also present on magento 2.1.6.

**Comment by phoenix128** [comment]
We finally managed to reproduce it. A fix is on the way

**Comment by phoenix128** [comment]
Sorry for making you wait for this fix. We did it ;) Upgrade to 1.1.4 .
