### ISSUE TITLE
How to Uninstall the extension

### ISSUE THREAD

**Issue by shawkatvirtuos** [magespecialist/m2-MSP_CashOnDelivery#22]
Hello ,

I cannot remove the extension by deleting the folder , if I am trying to do so , I am getting error in autoloader

**Comment by slackerzz** [comment]
Take a look at this link:
[http://devdocs.magento.com/guides/v2.1/install-gde/install/cli/install-cli-uninstall-mods.html](http://devdocs.magento.com/guides/v2.1/install-gde/install/cli/install-cli-uninstall-mods.html)

**Comment by shawkatvirtuos** [comment]
I have tried this but is getting stuck at Removing code from Magento codebase, can you please tell me if there is any other way ? why deleting the file giving an autoloader error when upgradingt

PHP Warning:  require(/var/www/html/magento2.test.com/trunk/vendor/msp/common/registration.php): failed to open stream: No such file or directory in /var/www/html/magento2.test.com/trunk/vendor/composer/autoload_real.php on line 60
PHP Fatal error:  require(): Failed opening required '/var/www/html/magento2.test.com/trunk/vendor/msp/common/registration.php' (include_path='/var/www/html/magento2.test.com/trunk/vendor/magento/zendframework1/library:/var/www/html/magento2.test.com/trunk/vendor/phpunit/php-file-iterator:/var/www/html/magento2.test.com/trunk/vendor/phpunit/phpunit:/var/www/html/magento2.test.com/trunk/vendor/symfony/yaml:.:/usr/share/php') in /var/www/html/magento2.test.com/trunk/vendor/composer/autoload_real.php on line 60

**Comment by slackerzz** [comment]
try ```composer remove msp/cashondelivery```

**Comment by shawkatvirtuos** [comment]
Thanks the same is working
