### ISSUE TITLE
Blank checktou page

### ISSUE THREAD

**Issue by lucav90** [magespecialist/m2-MSP_CashOnDelivery#24]
Hi,

i have installed your magento 2 module with the ftp method, but after this i have a white blank screen on checkout page.
What is the problem?

**Comment by giacmir** [comment]
Please look at you server's error log and copy the error message you find there.

**Comment by lucav90** [comment]
Hi,

the checkout is ready in this moment, but i don't view the cash on delivery payment on frontend of checkout page.

i have imported the csv but i don't view anything.

what is the problem?

**Comment by giacmir** [comment]
So your checkout page is not blank right? I'm closing this issue, please open another one for this second issue. (One issue = one problem)
