### ISSUE TITLE
don't view cash on delivery payment - frontend

### ISSUE THREAD

**Issue by lucav90** [magespecialist/m2-MSP_CashOnDelivery#25]
Hi,

i don't view the cash on delivery payment on frontend of checkout page.

i have imported the csv but i don't view anything.

what is the problem?

**Comment by giacmir** [comment]
When you upload your csv you should see the number of rules loaded, do you see it?

<img src="https://raw.githubusercontent.com/magespecialist/m2-MSP_CashOnDelivery/master/screenshots/screen2.png"/>

**Comment by lucav90** [comment]
yes, 2 rules

**Comment by giacmir** [comment]
Ok, so your csv is probably malformed, can you provide your csv content?

**Comment by lucav90** [comment]
[msp_cashondelivery(1).txt](https://github.com/magespecialist/m2-MSP_CashOnDelivery/files/1161684/msp_cashondelivery.1.txt)

**Comment by lucav90** [comment]
on db (table: msp_cashondelivery_table) the data are correct

**Comment by phoenix128** [comment]
Can you please tell us what was your install proceudeure? You tould us you used "the ftp" method, but this module should be installed using composer.

My guess is that you are missing some file or dependency.

**Comment by lucav90** [comment]
i have downloaded the zip on github, installed into app/code magento folder. the extension is visible and configurable on backend. the problem is on frontend.

i haven't composer on my server, i can't install this. so please tell me how can i solve the problem

**Comment by phoenix128** [comment]
Honestly I do not know, you should at least give us some error, if any, in your logfile/console.
You should make your developers to check in it to understand why it is not working with your checkout.

**Comment by lucav90** [comment]
but there are other files or addons not present on github?

if the files on github are all, i have the correct plugin installed. my magento is the default 2.1.0, no other checkout plugin.

**Comment by phoenix128** [comment]
This module depends on "msp/common" package too. But it should work anyway.
What I can suggest you is to double check your settings. This module has been deeply tested on 2.1.x and it should work out-of-the-box. If it does not something in the config could be missing.

**Comment by lucav90** [comment]
Hi,

i have installed the 'msp/common' and put there on 'app/code' but the problem is the same.

i have installed (with composer) your plugin on another website and i view all 2 dependencies.

what is the problems?

**Comment by andre-gra** [comment]
Hi,
I have had the same problem. I think that it could be caused by the OpCheckout, that maybe is not supported by the module. It is possible?

Kinds Regards

**Comment by shanavas786** [comment]
I cloned the repo to `app/code/MSP/CashOnDelivery`, `setup:upgrade`, it is working fine.
`msp/common` is not installed.

**Comment by phoenix128** [comment]
Can you please upgrade to version 1.1.8 and check this again?

**Comment by lucav90** [comment]
Hi have downloaded the last version on github page, but the problem is the same. it doesn't work.
