### ISSUE TITLE
Can't generate invoice when cashondelivery

### ISSUE THREAD

**Issue by jaMez83** [magespecialist/m2-MSP_CashOnDelivery#26]
Hi,

I can't invoice orders when it have cash on delivery charges.

Checking logs i get this error:

 [proxy_fcgi:error] [pid 20262] [client 88.9.142.123:63944] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getMethod() on null in /var/www/web2/web/vendor/msp/cashondelivery/Block/Sales/Cashondelivery.php:49\nStack trace:\n#0 /var/www/web2/web/vendor/magento/module-sales/Block/Order/Totals.php(58): MSP\\CashOnDelivery\\Block\\Sales\\Cashondelivery->initTotals()\n#1 /var/www/web2/web/vendor/magento/framework/View/Element/AbstractBlock.php(656): Magento\\Sales\\Block\\Order\\Totals->_beforeToHtml()\n#2 /var/www/web2/web/vendor/magento/framework/View/Layout.php(542): Magento\\Framework\\View\\Element\\AbstractBlock->toHtml()\n#3 /var/www/web2/web/vendor/magento/framework/View/Layout.php(518): Magento\\Framework\\View\\Layout->_renderBlock('invoice_totals')\n#4 /var/www/web2/web/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\\Framework\\View\\Layout->renderNonCachedElement('invoice_totals')\n#5 /var/www/web2/web/vendor/magento/fr...\n', referer: https://mydomain.com/admin/sales/order/view/order_id/99/key/d58f3d3768258e01a35b38232afa26e1d48e6a25a002ce5e46dd33c8d031d12e/

I was checking the problem and I have no clue.

Any idea?

Thanks in advance

**Comment by giacmir** [comment]
Hi @jaMez83 

thanks for your report, the issue has been solved in version 1.1.7
