### ISSUE TITLE
Checkout "Cash on delivery" fee always added on "order Summary" 

### ISSUE THREAD

**Issue by tanolalano** [magespecialist/m2-MSP_CashOnDelivery#27]
Hi there,
As in issue #21 on Magento 2.1.7 and with COD 1.1.7, the COD fee is always added without select the payament method.
Here a screenshot
![screenshots_checkout](https://user-images.githubusercontent.com/4384863/28991658-51978a3a-798b-11e7-9715-c4dc2f37fa5b.PNG)
The bug #21 seems still present on version 1.1.7
Regards

**Comment by phoenix128** [comment]
Hello @tanolalano , can you please check with version 1.1.8?

**Comment by tanolalano** [comment]
Solved on 1.1.8 and on magento 2.1.7 &  2.1.8.
Thank you

**Comment by tanolalano** [comment]
Please reopen, 
I note when a user is logged in the bug is still present as in cart as in checkout on Magento 2.1.8, PHP 7.0.18 .Thanks
![schermata 2017-08-22 alle 16 01 50](https://user-images.githubusercontent.com/4384863/29569329-7516fe20-8753-11e7-82b7-c0e065753d6c.png)
![schermata 2017-08-22 alle 16 02 24](https://user-images.githubusercontent.com/4384863/29569332-77e9065c-8753-11e7-9a2a-30385a214c1f.png)

**Comment by phoenix128** [comment]
Unable to reproduce, can you please provide a step-by-step procedure from a newly created cart?
