### ISSUE TITLE
Cash On Delivery fees not displaying the admin Sales Order 

### ISSUE THREAD

**Issue by Prad2703** [magespecialist/m2-MSP_CashOnDelivery#28]
Cash on delivery charges not displaying on the 
Order Summary on the Sales Order.

![2017-08-07](https://user-images.githubusercontent.com/29308276/29032803-7c96bc48-7bb0-11e7-8996-3e57bfc33915.png)

**Comment by giacmir** [comment]
Uhm... I have that line... Can you post me the payment method section of this order?

![image](https://user-images.githubusercontent.com/447940/29033061-16db4458-7b94-11e7-9631-43b4a3a2801e.png)

**Comment by Prad2703** [comment]
I didn't get you. Please tell me what you want to know exactly? Do you need a frontend Checkuot Payment method section screenshot?

**Comment by giacmir** [comment]
in the admin order view (the same of your screenshot), just above the ordered items list there is a "payment information" section. Can you send me a pic of that part of the page?

**Comment by Prad2703** [comment]
Please check the screenshot. 
![2017-08-07](https://user-images.githubusercontent.com/29308276/29055580-e89f28a2-7c1a-11e7-8699-7da4a830b49c.png)

**Comment by Prad2703** [comment]
Hey giacmir,

Could you please let me know whether it's fixed or not?

**Comment by phoenix128** [comment]
Hello @Prad2703 ,
please check against version 1.2.1 and see if it is fixed.
We were unable to reproduce this.
