### ISSUE TITLE
Extra amount is not included if MSP-COD is the only payment method

### ISSUE THREAD

**Issue by shanavas786** [magespecialist/m2-MSP_CashOnDelivery#29]
if MSP Cash On Delivery is the only payment method, additional charge is not included in order total

![only-msp](https://user-images.githubusercontent.com/5337197/29416252-28fe7cea-836e-11e7-89dc-072373ecf327.png)

**Comment by phoenix128** [comment]
Issue confirmed, thank you for reporting this. We are working on it.

**Comment by phoenix128** [comment]
Please upgrade to 1.1.8, this is fixed.

**Comment by shanavas786** [comment]
Thanks
