### ISSUE TITLE
On refreshment shipping address reset to default address

### ISSUE THREAD

**Issue by saiyadsalma** [magespecialist/m2-MSP_CashOnDelivery#3]
When we click on payment method and select COD option and if you refresh or reload the page shipping address is reset to default shipping address rather than it must be set to the selected address from address list. 
Another bug is that if i select COD and now i navigate back to shopping cart page it will show totals with cod fee but in total section no indication displayed for COD charge. So it is mismatch for cart total section.

Please help me out to fix it

**Comment by phoenix128** [comment]
Hello @saiyadsalma ,
we will try to reproduce it ASAP, can you please tell us the exact version of Magento you are using?

**Comment by saiyadsalma** [comment]
HI,
I am using Magento 2.0.7 version right now.

**Comment by phoenix128** [comment]
Hello @saiyadsalma ,
can you please try our new version 1.0.1 .

It has not been tested on 2.0.7, but it fixes serveral bugs.

**Comment by phoenix128** [comment]
Closed for inactivity.
