### ISSUE TITLE
On selecting shipping address getting web-api error

### ISSUE THREAD

**Issue by binnykumar** [magespecialist/m2-MSP_CashOnDelivery#31]
Next Exception: Report ID: webapi-599e7f3acc52e; Message: Warning: addcslashes() expects parameter 1 to be string, object given in C:\xamp1\htdocs\bodyshop\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php on line 296 in C:\xamp1\htdocs\bodyshop\vendor\magento\framework\Webapi\ErrorProcessor.php:195
Stack trace:
#0 C:\xamp1\htdocs\bodyshop\vendor\magento\framework\Webapi\ErrorProcessor.php(139): Magento\Framework\Webapi\ErrorProcessor->_critical(Object(Exception))
#1 C:\xamp1\htdocs\bodyshop\vendor\magento\module-webapi\Controller\Rest.php(219): Magento\Framework\Webapi\ErrorProcessor->maskException(Object(Exception))
#2 C:\xamp1\htdocs\bodyshop\var\generation\Magento\Webapi\Controller\Rest\Interceptor.php(24): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))
#3 C:\xamp1\htdocs\bodyshop\vendor\magento\framework\App\Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#4 C:\xamp1\htdocs\bodyshop\vendor\magento\framework\App\Bootstrap.php(258): Magento\Framework\App\Http->launch()
#5 C:\xamp1\htdocs\bodyshop\index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#6 {main} [] []

**Comment by phoenix128** [comment]
Issue confirmed, thank you. We are working on a fix.

**Comment by binnykumar** [comment]
Hi thank you for your quick response.

Please confirm as to when you will be able to fix this issue.

**Comment by binnykumar** [comment]
I am using version 2.1.5.

**Comment by phoenix128** [comment]
Please upgrade to 1.2.1, this is fixed.

**Comment by binnykumar** [comment]
Yay ! 
This is working now.
Thank you very much for your quick support.
