### ISSUE TITLE
Fee not displayed in new order email totals

### ISSUE THREAD

**Issue by Gchladek** [magespecialist/m2-MSP_CashOnDelivery#33]
Hello 
using Magento 2.1.7 I noticed that the cash on delivery amount is not displayed among the totals in new order email.
![totals](https://user-images.githubusercontent.com/7200161/29916154-3b7e1260-8e3e-11e7-88f9-710a067cfb0c.PNG)

It is however displayed correctly in the invoice pdf.
![totalspdf](https://user-images.githubusercontent.com/7200161/29916364-d38d287a-8e3e-11e7-8d8a-9da858b2ac9a.PNG)

Version msp/cashondelivery 1.2.2, msp/common 0.1.4

**Comment by phoenix128** [comment]
Please upgrade to 1.2.4, we fixed it
