### ISSUE TITLE
Question about order email

### ISSUE THREAD

**Issue by giorg** [magespecialist/m2-MSP_CashOnDelivery#37]
Hi,

customer asks me to remove from new order email the line "Cash On Delivery Tax", and the title "Pagamento in contrassegno" (because it's shown twice), is this possible?

Thanks

**Comment by phoenix128** [comment]
Hello @giorg ,
actually it seems it was an error during email rendering.

Please upgrade to version 1.2.4, ve just fixed it.

**Comment by giorg** [comment]
Hi,

thanks for your answer. I installed it through composer, how to upgrade?
Thanks a lot

**Comment by phoenix128** [comment]
Try with:

```
composer require msp/cashondelivery:1.2.4
php bin/magento setup:upgrade
```

**Comment by giorg** [comment]
I get this:

`composer require msp/cashondelivery:1.2.4
Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package msp/cashondelivery 1.2.4 exists as msp/cashondelivery[0.1.0, 0.2.0, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.2.0, 1.2.1, 1.2.2, dev-master, dev-shanavas786-add-region-support] but these are rejected by your constraint.

Installation failed, reverting ./composer.json to its original content.`

any hint?

**Comment by phoenix128** [comment]
Hello @giorg ,
try it now, packagist was out of date.

**Comment by giorg** [comment]
hi,

ok now the installation went fine, but when I try to complete order, I get an ajax error and cannot go on, maybe this screenshot helps?

![screen shot 2017-09-12 at 14 52 33](https://user-images.githubusercontent.com/332048/30326844-24b43ff6-97ca-11e7-9189-29c6f1e5cf34.png)

**Comment by phoenix128** [comment]
That is the request, see if you getsomething in response tab or if you get something in your error log.

**Comment by giorg** [comment]
this the response:

<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function getData() on null in /var/www/coronelli
/vendor/magento/module-payment/Block/Info.php:87
Stack trace:
#0 /var/www/coronelli/vendor/magento/module-payment/view/frontend/templates/info/default.phtml(13): Magento
\Payment\Block\Info-&gt;getSpecificInformation()
#1 /var/www/coronelli/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/corone
...')
#2 /var/www/coronelli/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View
\TemplateEngine\Php-&gt;render(Object(MSP\CashOnDelivery\Block\Info\CashOnDelivery), '/var/www/corone
...', Array)
#3 /var/www/coronelli/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View
\Element\Template-&gt;fetchView('/var/www/corone...')
#4 /var/www/coronelli/vendor/magento/framework/View/Element/AbstractBlock.php(659): Magento\Framework
\View\Element\Template-&gt;_toHtml()
#5 /var/www/coronelli/vendor/magento/module-payment/Helper/Data.php(215): Magento\Framework\View\Element
\AbstractBlock- in <b>/var/www/coronelli/vendor/magento/module-payment/Block/Info.php</b> on line <b
>87</b><br />
{"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/1493178814345"
}]}}

**Comment by phoenix128** [comment]
Our fault, sorry for this.
Upgrade to 1.2.5, it should work.

**Comment by giorg** [comment]
no problem, you guys are great, thanks a lot!
