### ISSUE TITLE
REST PUT selected-payment-method return 404

### ISSUE THREAD

**Issue by stalica** [magespecialist/m2-MSP_CashOnDelivery#4]
When I choose COD method in checkout,  I get 404 for this link: PUT http://domain.com/rest/default/V1/guest-carts/255822baef9b805cc52a7c5d8358e37b/selected-payment-method
{"cartId":"255822baef9b805cc52a7c5d8358e37b","method":{"method":"msp_cashondelivery","po_number":null
,"additional_data":null}}

Where is the problem?
Magento 2.1.1
PHP 5.6

**Comment by giacmir** [comment]
I can't reproduce your issue. Can you please provide some additional information?
- what is your server operating system?
- do you have customized checkout theme or flow?
- are you using sample data?
- does this happens also with other payment methods e/g paypal?
- Is the api route present in /vendor/magento/module-quote/etc/webapi.xml at line 289?

Thanks

**Comment by stalica** [comment]
Server: VPS debian-7.0-x86_64-DA_PL_IMAPv2 
default chceckout and theme
not using sample data
other payment method works OK (paypal, default COD, bank transfer do not produce PUT selected-payment-method in REST API)
line 289 is route url="/V1/guest-carts/:cartId/selected-payment-method" method="PUT"

Thanks

**Comment by stalica** [comment]
I think this may be a problem with the configuration of hosting, I sent a notification to the administrator, I'll know if the problem resolves.

**Comment by stalica** [comment]
Problem solved. The reason was the server settings to redirect all traffic PUT on 404.

Thanks!

**Comment by Tristan-N** [comment]
I have the same issue. Note: it only happens when I haven't entered my address yet. With blank addressfields the COD doesn't work (loading until end of time) which generated the same error as @stalica mentioned. 
I'll let you know if the solution mentioned by @stalica worked for me.
