### ISSUE TITLE
Problem in cart and checkout summary

### ISSUE THREAD

**Issue by arioch1984** [magespecialist/m2-MSP_CashOnDelivery#40]
Hi!
Thank's for our great module, really usefull!

I have a problem with the tax amount in cart and checkout summary, in fact I could see if if set an additional fee with your great module and I select the cash on delivery (MSP) method during checkout, I could see a correct calculated tax total, but if I expand the grand total details accordion the sum of the various tax classes rates isn't right.

For example if I am buying an object for 33€ using IVA 4% tax and I set a 6€ shopping amount (taxed as 22% IVA) and I set a 3€ cash on delivery extra fee, I see:
- total taxes: 2,89€
- IVA 4%: 1,27€
- IVA 22%: 1,08€ 

But as you can see 1,27 + 1,08 = 2,35 differ from 2,89, in 22% tax class there isn't the extra fee tax, but the tax fee is in the total calculation.

Please may you help me with this problem?

I tried to solve it by myself but I could not see any Magento best way solution.

I think the problem is the module correctly add msp_cod_tax_amount to total tax calculation but not register the same value to the 22% tac class who is the default shipping tax class is settled in my magento installation (if I saw right the module uses the default shipping tax class, right?)

Thank's a lot in advantage.

Best regards.

**Comment by phoenix128** [comment]
Hello @arioch1984 ,
can you please send us your tax settings inside Magento?

A screenshot is fine.

**Comment by arioch1984** [comment]
Hi!

First thank's a lot for your quick reply!

I will attach to this post two screens with tax rules and rates.

![screenshot 2017-09-14 09 50 19](https://user-images.githubusercontent.com/5476141/30418178-66cca09a-9932-11e7-882d-59ed3834eb56.png)
![screenshot 2017-09-14 09 50 28](https://user-images.githubusercontent.com/5476141/30418179-66f44988-9932-11e7-99ac-2bf4aa957f2e.png)
