### ISSUE TITLE
Fees were ignored on checkout Magento 2.1.8

### ISSUE THREAD

**Issue by ghost** [magespecialist/m2-MSP_CashOnDelivery#42]
### Preconditions
1.  Cloud VPS Centos 7
2.  Magento 2.1.8, PHP 7.0 MySQL 5

### Steps to reproduce

1. Installing msp_CashOnDelivery via composer,
2.  configuring fee for all country (using wildcards) with csv upload and enabling payment method
3.  trying to placing order selecting COD payment method via Backend or Frontend

### Expected result
1. order total with cash on delivery fee added

### Actual result
1. no charges applied

Hi, 
I'm trying to use your extension on Magento 2.1.8 but it seems doesn't work.
I followed the instruction to install and get it via composer.
I've set the fee according the instruction but, when I try to place an order, no fee is added on my total.
The payment method is correct set, but fees are no added to the total even if I place the order from the magento backend.
This is the configuration I use: 
![image](https://user-images.githubusercontent.com/5671164/30651324-a337bcd4-9e25-11e7-8f5e-32ddae097681.png)

and a screenshot from frontend:
![image](https://user-images.githubusercontent.com/5671164/30651082-f2b9319e-9e24-11e7-90f3-d8e13c22f589.png)

**Comment by giacmir** [comment]
Hi @Sansone87 

is that the default Magento Checkout Module?

**Comment by ghost** [comment]
yes, with a different template.
Even if I try to place an order via backend I get the same result.

**Comment by giacmir** [comment]
Some checks:

1. Are you rules correctly imported? 
![image](https://user-images.githubusercontent.com/447940/30652631-287c37d2-9e29-11e7-841f-f43c0fe829b3.png) (you should have a little number below the upload button)
2. are there javascript errors in checkout page?
3. If you put other country than italy in your address does the fee apply?
4. in var/log/exception.log are references to this module present?

**Comment by ghost** [comment]
1. Yes:
![image](https://user-images.githubusercontent.com/5671164/30653537-a427ca2a-9e2b-11e7-9a3d-d21db9642d2a.png)
2. no, no javascript execption.
3. I tried with different one, no fees applied
4. no errors refeering check out or payment method or msp extension

**Comment by ghost** [comment]
Hello, 
I've tried to install the extension on magento 2.1.6, and it works!
The check out page is different, is in three step, on the 2.1.9 is one step checkout.
I suppose the extension is not fully compatible with this magento version.

**Comment by giacmir** [comment]
Magento2 has always had two steps and no such change was introduced recently. Are you sure that you don't have some customization?

**Comment by ghost** [comment]
I've tried to uninstall the theme and set the default theme back but nothing change.
So I downgraded Magento to 2.1.7 and it works fine!
It's so odd, reinstalling Magento 2.1.8 I only get the one step check out.
