### ISSUE TITLE
Fatal-Error while updating cart

### ISSUE THREAD

**Issue by attheCube** [magespecialist/m2-MSP_CashOnDelivery#43]
Fatal error occurred while updating cart

### Preconditions
1. Magento Versions 2.1.3 and 2.1.9
2. msp/cod versions above 1.1.7
3. PHP version 7.0.13
4. Apache 2.4.x
5. Mode: developer

### Steps to reproduce
1. Put a product into cart
2. Update the cart

### Expected result
1. Cart is updated

### Actual result
1. ![fireshot screen capture 001checkout_cart_updatepost](https://user-images.githubusercontent.com/4963336/31501992-18d135f4-af6c-11e7-9add-f38bb325ffcd.png)

**Comment by giacmir** [comment]
Hi @attheCube 

what is `Tripuls/Sales` and what it does? Seems like a custom that does something unusual.

**Comment by attheCube** [comment]
Hi @giacmir,
I have to appologize.
I didn't see the Module made by a collegue of mine, which fixed a failure of an earlier version, but crashed since version 1.1.8 .

**Comment by phoenix128** [comment]
Hello @attheCube ,
no problem :+1: , happy to know you understood where the problem was.
