### ISSUE TITLE
getting php version error while installing via composer

### ISSUE THREAD

**Issue by rajeevjan1991** [magespecialist/m2-MSP_CashOnDelivery#45]
### Preconditions

1. useing  xampp for windows
2. magento 2.2, PHP -7.1.8 and mysql5.0

### Actual result

1. 
![screenshot 153](https://user-images.githubusercontent.com/33253321/32221378-54106f24-be5b-11e7-888c-8b2a2911bc58.png)

**Comment by phoenix128** [comment]
Hello @rajeevjan1991 ,
this has been fixed in 1.2.9 .
Thanks
