### ISSUE TITLE
Can we use Pincodes for charging COD Fee

### ISSUE THREAD

**Issue by vinaykumar9999** [magespecialist/m2-MSP_CashOnDelivery#46]
Can we use CSV for adding pincodes and add COD charge according to that.

**Comment by shanavas786** [comment]
currently not. But you can implement it easily.
#30 may give you some insight.

**Comment by phoenix128** [comment]
Hello @vinaykumar9999 ,
do you mean postcodes?

**Comment by vinaykumar9999** [comment]
Hi phoenix128

Thanks for the correction, can we use csv for the postcodes and add COD charge according to postcodes
