### ISSUE TITLE
COD-Fee not showing in invoice-Email

### ISSUE THREAD

**Issue by JensNi** [magespecialist/m2-MSP_CashOnDelivery#47]
### Preconditions

1. Magento 2.1.7, php 7
2. Extension-Version 1.2.9

### Steps to reproduce

1. Place order
2. Look at "New order email" - COD Fee is showing up in totals (i just changed position to "before=tax" in xml)
3.  Create invoice in admin-backend

### Expected result

1. Csutomer receiving invoice email including COD fee.

### Actual result

1. COD fee is missing in invoice mail, but Tax and Grandtotal are correct
![image](https://user-images.githubusercontent.com/24682788/32784506-4f56155c-c94f-11e7-902c-b6bd49fd0cc1.png)

**Comment by phoenix128** [comment]
Hello @JensNi  ,
please refer to new module mantainer "it4mage".

https://github.com/it4mage/CashOnDelivery

We moved this module under the responsability of it4mage group.
