### ISSUE TITLE
Tax in Order Review/Summary

### ISSUE THREAD

**Issue by JensNi** [magespecialist/m2-MSP_CashOnDelivery#48]
### Preconditions

1. Magento 2.1.7, php 7
2. Extension-Version 1.2.9
3. Set up different tax rates for different countries (20% FR, 19% DE ->this is default).
4. Tax gets calculated by shipping-country

### Steps to reproduce

1. Place article in cart and proceed to checkout 
2. Choose shipping country different from your default country/tax-country - so tax rate is 20%, not default 19%

### Expected result

1. Order Summary should calculate tax based on the correct tax rate for this country

### Actual result

1. tax gets calculated with the default tax rate

![image](https://user-images.githubusercontent.com/24682788/32796424-053b2c3a-c96f-11e7-8f26-5c609ca5311b.png)

2. It should be a total of 35,00 € and a tax amount off 5,833 € - When choosing the payment method itself, it gets caclulated correctly but not in the summary.

![image](https://user-images.githubusercontent.com/24682788/32796498-37e9dcc6-c96f-11e7-9c1d-4ced21396848.png)

**Comment by phoenix128** [comment]
Hello @JensNi  ,
please refer to new module mantainer "it4mage".

https://github.com/it4mage/CashOnDelivery

We moved this module under the responsability of it4mage group.
