### ISSUE TITLE
add to cart and login not working after installing this extension

### ISSUE THREAD

**Issue by rajeevjan1991** [magespecialist/m2-MSP_CashOnDelivery#49]
i have installed this extension in magento 2.2.0,
everything working fine but when i try to login its showing processing icon and also on add to cart button click.
![screenshot 184](https://user-images.githubusercontent.com/33253321/33923516-a5e72528-dff7-11e7-86fe-51ab94a7cc7f.png)
![screenshot 185](https://user-images.githubusercontent.com/33253321/33923517-a617f0d6-dff7-11e7-8a0d-6aecf74377c5.png)

and after that website getting slow and display only loading on home page access

**Comment by rajeevjan1991** [comment]
you can also see it here www.sporting8.com

**Comment by phoenix128** [comment]
This issue should be investigated in your checkout procedure.
