### ISSUE TITLE
Can't translate "Cash on delivery" in Order Summary (Checkout)

### ISSUE THREAD

**Issue by stalica** [magespecialist/m2-MSP_CashOnDelivery#5]
Use Inline translate
![przechwytywanie](https://cloud.githubusercontent.com/assets/22389052/19116906/5ca4e70a-8b17-11e6-8031-28944f705e19.PNG)

**Comment by phoenix128** [comment]
Hello @stalica ,
seems like inline translation is not working for this kind of totals, but you can create a translation file in your theme. We already tried it and it is working.

Check out here to find how: http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/translations/xlate.html
