### ISSUE TITLE
Change Label 'msp_cashondelivery'

### ISSUE THREAD

**Issue by giacomoleopardi** [magespecialist/m2-MSP_CashOnDelivery#50]
Hi,

I use MSP_CashOnDelivery with external module of OneStepCheckout in italian store.
How I modify string 'msp_cashondelivey' with an other string?

Thanks!

![msp](https://user-images.githubusercontent.com/32741287/34639403-0885923c-f2e0-11e7-8f18-687225cc2ee7.png)

**Comment by phoenix128** [comment]
Hello @giacomoleopardi  ,
please refer to new module mantainer "it4mage".

https://github.com/it4mage/CashOnDelivery

We moved this module under the responsability of it4mage group.
