### ISSUE TITLE
Error on Customer Billing Agreement Page

### ISSUE THREAD

**Issue by adkanojia** [magespecialist/m2-MSP_CashOnDelivery#51]
### Preconditions

1. PHP 7
2. Magento 2.1.8

### Steps to reproduce

1. Install/Enable Extension
2. Setup CashOnDelivery Charges
3. Login to customer account and go to Dashboard->Billing Agreements

### Expected result

1. It should open the page

### Actual result

1. Fatal error: Uncaught Error: Call to a member function getItemVirtualQty() on null in .../app/code/MSP/CashOnDelivery/Model/Payment.php on line 43
[Screenshot, logs]

![screen shot 2018-01-11 at 10 40 52 pm](https://user-images.githubusercontent.com/17718474/34837403-b4bb183a-f720-11e7-9673-7a476c86a17e.png)

I've tried this on 2 different magento installations:
1. With custom theme and other cutomizations
2. Default Magento setup
Both give same result.

Regards..
Akash Kanojia

**Comment by phoenix128** [comment]
Hello @adkanojia ,
please refer to new module mantainer "it4mage".

https://github.com/it4mage/CashOnDelivery

We moved this module under the responsability of it4mage group.
