### ISSUE TITLE
Cart/Payment Summary label is not translated

### ISSUE THREAD

**Issue by ilevennet** [magespecialist/m2-MSP_CashOnDelivery#53]
The label in cart/payment summary is not translated but remain "Cash on Delivery" 

### Magento
1. Magento 2.2.2 
2. "msp/cashondelivery": "^1.2",

### Check next screenshot

![schermata 2018-01-22 alle 20 33 21](https://user-images.githubusercontent.com/1394124/35240531-05e5e6ea-ffb4-11e7-9b01-e9e767aa438a.jpg)

![schermata 2018-01-22 alle 20 39 40](https://user-images.githubusercontent.com/1394124/35240650-681a943c-ffb4-11e7-92ed-5f18a94501bc.jpg)

### Expected result
1. Cart summary label equals Label in settings

**Comment by phoenix128** [comment]
Hello @zenomordiante ,
please refer to new module mantainer "it4mage".

https://github.com/it4mage/CashOnDelivery

We moved this module under the responsability of it4mage group.
