### ISSUE TITLE
COD doesn't show in checkout

### ISSUE THREAD

**Issue by etessari** [magespecialist/m2-MSP_CashOnDelivery#54]
The method does not show on checkout, it seems because method display is based on default billing instead of current selected address.

### Preconditions
1. Magento CE 2.1.11
2. Module version dev-master:836ea69

### Steps to reproduce
1. login to frontend
2. from customer reserved area add new default address (specific COD country not allowed)
3. go to checkout select different address with allowed COD country
4. go to payment step

### Expected result
1. COD method visible

### Actual result
1. COD method doesn't show

**Comment by daniloargentiero** [comment]
This module has been moved under the responsibility of "it4mage" group. Please check this URL: https://github.com/it4mage/CashOnDelivery
