### ISSUE TITLE
Uncaught Error: Call to a member function getItemVirtualQty() 

### ISSUE THREAD

**Issue by ahmedzainsalem** [magespecialist/m2-MSP_CashOnDelivery#55]
Please help me!
This is what i' m facing when try to open payment page

<b>Fatal error</b>:  Uncaught Error: Call to a member function getItemVirtualQty() on null in /home/tshirtfa/public_html/vendor/msp/cashondelivery/Model/Payment.php:43
--
  | Stack trace:
  | #0 /home/tshirtfa/public_html/vendor/magento/module-payment/Helper/Data.php(140): MSP\CashOnDelivery\Model\Payment-&gt;isAvailable(NULL)
  | #1 /home/tshirtfa/public_html/vendor/magento/module-vault/Model/Ui/VaultConfigProvider.php(84): Magento\Payment\Helper\Data-&gt;getStoreMethods('1')
  | #2 /home/tshirtfa/public_html/vendor/magento/module-vault/Model/Ui/VaultConfigProvider.php(60): Magento\Vault\Model\Ui\VaultConfigProvider-&gt;getVaultPaymentMethodList()
  | #3 /home/tshirtfa/public_html/vendor/magento/module-checkout/Model/CompositeConfigProvider.php(32): Magento\Vault\Model\Ui\VaultConfigProvider-&gt;getConfig()
  | #4 /home/tshirtfa/public_html/vendor/magento/module-checkout/Block/Cart/Shipping.php(54): Magento\Checkout\Model\CompositeConfigProvider-&gt;getConfig()
  | #5 /home/tshirtfa/public_html/vendor/magento/module-checkout/view/frontend/templates/cart/shipping.phtml(28):  in <b>/home/tshirtfa/public_html/vendor/msp/cashondelivery/Model/Payment.php</b> on line <b>43</b><br />

**Comment by phoenix128** [comment]
Please provide some additional information, like Magento version number, install procedure, configuration, ecc..

**Comment by ahmedzainsalem** [comment]
Hi,

thanks for your relpay.  

**Preconditions**
Magento CLI version 2.1.2
PHP PHP 7.0.27
MySQL Ver 14.14

**Steps to reproduce**

I've added  MSP_CashOnDelivery module in Magento2  with composer 

 composer require msp/cashondelivery
 composer update
 php bin/magento module:enable MSP_CashOnDelivery
 php bin/magento setup:upgrade
 php bin/magento cache:flush

**Actual result**
After completing the download process

-  i logged into the backend page
-Go to Stores > Configuration > Sales > Payment Methods > Cash On Delivery 
-Enabled > YES
-download msp_cashondelivery.csv file
-Change the CSV file and upload using the "browse" button and Save
-Go home page and choose a product then go to the page
-And when entering the page of checkout,I did not find anything that was white
-click view source , i found that error

thanks alot

**Comment by daniloargentiero** [comment]
This module has been moved under the responsibility of "it4mage" group. Please check this URL: https://github.com/it4mage/CashOnDelivery

**Comment by ahmedzainsalem** [comment]
Hi,

I think the reason for this error is related to the database, so please send me database queries that related to this model

Many thanks
