### ISSUE TITLE
Fee only sho tax excluded

### ISSUE THREAD

**Issue by masfiore** [magespecialist/m2-MSP_CashOnDelivery#56]
There is a possibility to sho only the fee with tax excluded, but if you have in checkout all tax included only this field show tax excluded.

### Preconditions
Magento 2.2 Nginx
### Steps to reproduce
In checkout when select metod Cash on delivery, the fee is only tax excluded

### Expected result
There is a possibility to show tax included?

**Comment by giacmir** [comment]
This issue was moved to it4mage/CashOnDelivery#6
