### ISSUE TITLE
MSP_CashOnDelivery module break Component Manager 

### ISSUE THREAD

**Issue by ahmedzainsalem** [magespecialist/m2-MSP_CashOnDelivery#57]
**Preconditions**
PHP 7.0.27
Magento 2.1.2

**Steps to reproduce**

I installed the extension  via Composer : composer require msp/cashondelivery
Go to System -> Tools -> Web Setup -> Component Manager

**Expected result**

No PHP error. The list of installed extensions is presented.

**Actual result**
The spinner is loading all the time.
You can see that the url /setup/index.php/componentGrid/components returns the following PHP error:

An error occurred

An error occurred during execution; please try again later.

Additional information:

RuntimeException

File:
public_html/setup/src/Magento/Setup/Model/PackagesData.php:88
Message:
Couldn't get available versions for package msp/cashondelivery
Stack trace:
#0 public_html/setup/src/Magento/Setup/Controller/ComponentGrid.php(98): Magento\Setup\Model\PackagesData->syncPackagesData()
#1 public_html/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(82): Magento\Setup\Controller\ComponentGrid->componentsAction()
#2 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#3  public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#4  /public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#5  /public_html/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#6  public_html/vendor/zendframework/zend-mvc/src/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#7 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#8 /public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#9  public_html/vendor/zendframework/zend-eventmanager/src/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#10 public_html/vendor/zendframework/zend-mvc/src/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#11 public_html/setup/index.php(31): Zend\Mvc\Application->run()
#12 {main}

**Comment by ahmedzainsalem** [comment]
[https://github.com/magento/magento2/pull/9692/files](url)
This fix worked for me.

**Comment by giacmir** [comment]
This issue was moved to it4mage/CashOnDelivery#5
