### ISSUE TITLE
Price in Sales Order and Backend is wrong when exclude taxes

### ISSUE THREAD

**Issue by ilevennet** [magespecialist/m2-MSP_CashOnDelivery#58]
### Preconditions
1. Magento 2.2.2
2. Fee is 6€ Taxes included
3. Check on Delivery csv:
country,region,from_amount,fee,website
*,*,0.0000,4.92,*

### Steps to reproduce
1. I have set to display Subtotals Excluded taxes as:
![schermata 2018-02-26 alle 10 16 54](https://user-images.githubusercontent.com/1394124/36662275-1f75ed86-1ade-11e8-8991-c7d50665b3fa.jpg)

![schermata 2018-02-26 alle 10 17 01](https://user-images.githubusercontent.com/1394124/36662282-2434f8c6-1ade-11e8-81c4-fb836d7beb0d.jpg)

### Expected result
1. Price in cart and checkout is ok, but in Backend orders and Sales mail is wrong

### Actual result
1. CHECKOUT IS OK
![img-7381](https://user-images.githubusercontent.com/1394124/36662374-857c84f0-1ade-11e8-8fac-b3fec6ac1ccb.JPG)

2. SALES MAIL IS WRONG
![img-7383](https://user-images.githubusercontent.com/1394124/36662396-917d1f4e-1ade-11e8-823d-e453abd8ede3.JPG)

3. BACKEND AREA ORDER IS WRONG
![img-7382](https://user-images.githubusercontent.com/1394124/36662409-a025d57c-1ade-11e8-944a-d89d1526a08f.JPG)

4. TOTALS IS OK

**Comment by giacmir** [comment]
This issue was moved to it4mage/CashOnDelivery#4
