### ISSUE TITLE
Problem db, table structure and examples data

### ISSUE THREAD

**Issue by lucav90** [magespecialist/m2-MSP_CashOnDelivery#6]
Hi,

i have installed Your module with manually solution. We have installed the module but we have problem about db schema e db example data.
I create manually the table 'msp_cashondelivery_table' with data, i configure and enabled the module on backend of magento but in frontend i don't view it, nothing!

How can i resolve? What is the structure and sample data of database tables?

Regards,

**Comment by slackerzz** [comment]
did you run `bin/magento setup:upgrade`?

**Comment by lucav90** [comment]
yes!
But i had a sql error. So i have created the table manually

**Comment by slackerzz** [comment]
Which Magento version are you using?

**Comment by lucav90** [comment]
Magento 2.0.7 but i solved!
Another problem. I don't view the 'Cash on delivery' on cart list items in checkout page.

**Comment by phoenix128** [comment]
Last question is dauplicated question of issue #7. Closing this thread.
