### ISSUE TITLE
Facing issue msp_cashondelivery with pincode availability module .

### ISSUE THREAD

**Issue by vajor-saurabh** [magespecialist/m2-MSP_CashOnDelivery#61]
### Preconditions

1. 
2. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by vajor-saurabh** [comment]
Hi I have third part plugin pincode checker . Its works fine bydefault  COD method but facing issue with msp_cashdeliervery plugin , How to check in checkout page if pincode is set in pincode checker module then msp_deliery module should enable in checkout , please tell me where we check inside this module to full fill our requirement, means pincode if available in backend then msp_delievery is enable if not exit pincode then not show option in checkout ..

**Comment by vajor-saurabh** [comment]
Hi,
I have downloaded your plugin msb_cashondelivry and i am using also one of the third party module for pincode checking availability so when we disable your plugin then the pincode availability module working fine but when we enable your plugin then faces issue like in checkout page cash on delivery option still comes when we enable your plugin so please suggest me which file I will change sothat the same functionality pincode availability module will work with your module .
Please suggest me.

**Comment by giacmir** [comment]
Hi @vajor-saurabh This project is now located at https://github.com/it4mage/CashOnDelivery

We don't provide support here anymore. Please open another issue on the project indicated above.
