### ISSUE TITLE
Magento 2.2.3 CE, price is zero when adding to cart

### ISSUE THREAD

**Issue by Baracuda011** [magespecialist/m2-MSP_CashOnDelivery#62]
### Preconditions
1. Magento 2.2.3 CE
2. PHP 7.0.28
3. MySQL 5.0.12

### Steps to reproduce
1. Upgrade from 2.1.3 CE to 2.2.3 CE
2. Try to add any product to cart

### Expected result
1. Mini cart should appear with the added product

### Actual result
1. Product is not added to cart
2. Ajax call (/en/customer/section/load/?sections=cart&update_section_id=false&_=1525081553687) endlessly loads.

/en/customer/section/load/?sections=cart&update_section_id=false&_=1525081553687

cart
{
	summary_count: 0,
	subtotalAmount: null,
	subtotal: "<span class="price">AED0.00</span>",
	data_id: 1525081565,
	extra_actions: "",
	isGuestCheckoutAllowed: true,
	**THIS => items: [] <= THIS**,
	possible_onepage_checkout: true,
	subtotal: "<span class="price">AED0.00</span>",
	subtotalAmount: null,
	subtotal_excl_tax: "<span class="price">AED0.00</span>",
	subtotal_incl_tax: "<span class="price">AED0.00</span>",
	summary_count: 0,
	website_id: "1"
}

To add a detailed description here:

I have a very strange issue. After upgrading from 2.1.3 to 2.2.3 CE I've noticed one strange issue, which is as I found out, related to MSP_CashOnDelivery module. But please let me explain the scenario.

When the module is disabled, add to cart work properly, and mini-cart is displayed after product is added to cart. But, when the module is enabled data this is not the case.

Here are the call and the response:

/en/customer/section/load/?sections=cart&update_section_id=false&_=1525081553687

cart
{
	summary_count: 0,
	subtotalAmount: null,
	subtotal: "<span class="price">AED0.00</span>",
	data_id: 1525081565,
	extra_actions: "",
	isGuestCheckoutAllowed: true,
	**THIS => items: [] <= THIS**,
	possible_onepage_checkout: true,
	subtotal: "<span class="price">AED0.00</span>",
	subtotalAmount: null,
	subtotal_excl_tax: "<span class="price">AED0.00</span>",
	subtotal_incl_tax: "<span class="price">AED0.00</span>",
	summary_count: 0,
	website_id: "1"
}

Magento Community also confirmed my scenario, please have a look at:
https://community.magento.com/t5/Magento-2-x-Programming/Magento-2-2-3-CE-price-is-zero-when-adding-to-cart/m-p/93291#M4305

Thank you very much.

Cheers,
Nemanja.

**Comment by raffoitaly** [comment]
Same problem for me.

any news?

Cheers,
Raffaello

**Comment by giacmir** [comment]
This issue was moved to it4mage/CashOnDelivery#3
