### ISSUE TITLE
Problem string 'Cash on delivery' cart on checkout page

### ISSUE THREAD

**Issue by lucav90** [magespecialist/m2-MSP_CashOnDelivery#7]
Hi,

I don't view the string 'Cash on delivery' on cart list items in checkout page.

How can i resolve?

Regards,

**Comment by phoenix128** [comment]
Hello @lucav90 ,
you will not see any extra row in the cart items, but in the cart totals.

Did you configure your rates?

**Comment by lucav90** [comment]
Hi,
configure your module and works, but i want the string 'Cash on delivery' on cart in checkout page.
I view your attachment (screen4.png) where i see this row.

Luca

**Comment by phoenix128** [comment]
I am sorry @lucav90 , I did not understand your needings. Do you mean you do not see "Cash on delivery" on right side of your checkout page?

If yes you are probably missing something in the installation or you did not correctly configured our module.

**Comment by lucav90** [comment]
Hi @phoenix128, yes correct. I have installed your module manually, i use magento setup:upgrade, enabled the module in magento admin (Configuration->advanced->advanced).
There are other Magento instruction o command to use for a correct installation?

**Comment by phoenix128** [comment]
Did you upload your cash on delivery fees CSV file from backend?

**Comment by lucav90** [comment]
Yes, sure. But first, we had an sql error becouse there wasn't a sql table and your module not works. Then, I have created this table and works.

**Comment by phoenix128** [comment]
Ok, so if you had SQL problems, you may be missing the extra columns in the order items information.
And I far as I understood you did not use composer.

My suggestion to fix is:
- Manually delete `app/code/MSP/CashOnDelivery` path
- From phpmyadmin run: `delete from setup_module where module='MSP_CashOnDelivery'`
- From phpmyadmin run: `drop table msp_cashondelivery_table`
- Open `app/etc/config.php` and remove the line containing `MSP_CashOnDelivery`

Now, if everything is ok, the module is correctly uninstalled.

After this procedure install it using composer:

```
composer require msp/cashondelivery
php bin/magento setup:upgrade
```

Now you have to enable the method and upload your cash on delivery fees CSV.

Flush your cache and try.

Please make sure you correctly undrestood what you are going to do in every single step. A wrong procedure may cause damage to your e-commerce. If you are not confident please make a DB backup before you proceed.

**Comment by lucav90** [comment]
Hi,

thanks. I have solved!

Another question. How can i display the price with taxes (in summary cart on checkout page)?

**Comment by phoenix128** [comment]
Hi @lucav90 ,
as far as now it does not support this feature since taxes are added to **taxes total**.

If you wish you can modify [https://github.com/magespecialist/m2-MSP_CashOnDelivery/blob/master/Model/Total/Quote/Cashondelivery.php](url) and change the `fetch` method to display taxes.
